### ISSUE TITLE
Warning from Julia 1.1 on "eachcol"

### ISSUE THREAD

**Issue by evveric** [joshday/OnlineStatsBase.jl#9]
Once I import OnlineStatsBase, the follow warning occur from Julia terminal

WARNING: both OnlineStatsBase and Base export "eachcol"; uses of it in module OnlineStats must be qualified

is there a way to remove this? Is it because the Julia Base also has a method called "eachcol"?

**Comment by joshday** [comment]
Yes, but I believe that was fixed a while ago.  Can you update your version of OnlineStats?

**Comment by evveric** [comment]
it still occurs, I am using Julia 1.1 with:

`filter(x -> occursin(r"Online", first(x)), Pkg.installed())`


Dict{String,Union{Nothing, VersionNumber}} with 2 entries:
  "OnlineStatsBase" => v"0.10.2"
  "OnlineStats"     => v"0.23.0"

is v 0.10.2 enough?

**Comment by joshday** [comment]
That release is from April.  There are several newer versions of OnlineStats(Base) you should be able to get.

Did you try running `Pkg.update()`?

**Comment by evveric** [comment]
we can close this case, Now I am at v0.32.0 and I dont see this error again
